# based on https://github.com/gavinzhou/ci-minikube
# https://github.com/kubernetes/minikube#linux-continuous-integration-without-vm-support
version: 2

jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    environment:
      K8S_VERSION: v1.10.0
      KUBECONFIG: /home/circleci/.kube/config
      MINIKUBE_VERSION: v0.29.0
      MINIKUBE_WANTUPDATENOTIFICATION: false
      MINIKUBE_WANTREPORTERRORPROMPT: false
      MINIKUBE_HOME: /home/circleci
      CHANGE_MINIKUBE_NONE_USER: true

    working_directory: ~/repo
          
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo rm /var/lib/dpkg/lock
            sudo dpkg --configure -a
            sudo apt-get install software-properties-common
            sudo add-apt-repository ppa:fkrull/deadsnakes
            sudo apt-get update
            sleep 5
            sudo rm /var/lib/dpkg/lock
            sudo dpkg --configure -a
            sudo apt-get install python3.5
            sleep 5
            python -m pip install -r requirements.txt
        
      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      
      - run:
          name: install docker
          command: |
            # curl -fsSL get.docker.com | sh

      - run:
          name: run tests
          command: |
            python -m pytest tests/test_rsvpapp.py  
            
      - run:
          name: build image
          command: |
            docker build -t vishalcloudyuga/rsvpapp .
            cat my_password.txt | docker login --username vishalcloudyuga --password-stdin
            docker push vishalcloudyuga/rsvpapp:latest
      

