apiVersion: 0.1.0
environments:
  default:
    destination:
      namespace: default
      server: https://kubernetes.default.svc
    k8sVersion: v1.12.1
path: rsvp
kind: ksonnet.io/app
name: rsvpapp
